Handle linter failure gracefully

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,15 +38,15 @@ runs:
         linters=('ruff' 'flake8' 'pylint' 'mypy' 'pyright' 'pytype' 'fixit')
         if [[ "${linters[*]}" =~ (^|[^[:alpha:]])${INPUTS_LINTER}([^[:alpha:]]|$) ]]; then
           if [[ "${INPUTS_LINTER}" == "fixit" ]]; then
-            "${PYTHON_CMD}" -mpip install "fixit >1" --pre || echo "::error::fixit 2 is not available for python ${INPUTS_PYTHON_VERSION}"
+            "${PYTHON_CMD}" -mpip install "fixit >1" --pre || echo "::error::fixit 2 is not available for Python ${INPUTS_PYTHON_VERSION}"
           else
-            "${PYTHON_CMD}" -mpip install "${INPUTS_LINTER}" || echo "::error::${INPUTS_LINTER} failed to install for ${INPUTS_PYTHON_VERSION}"
+            "${PYTHON_CMD}" -mpip install "${INPUTS_LINTER}" || echo "::error::${INPUTS_LINTER} failed to install for Python ${INPUTS_PYTHON_VERSION}"
           fi
           if [[ "${INPUTS_LINTER}" == "flake8" ]]; then
             "${PYTHON_CMD}" -mpip install "${GITHUB_ACTION_PATH}"/flake8_sarif_formatter
           fi
 
-          "${PYTHON_CMD}" "${GITHUB_ACTION_PATH}"/python_lint.py "${INPUTS_LINTER}" --target="${INPUTS_TARGET}" --output="${GITHUB_WORKSPACE}/${INPUTS_OUTPUT}"
+          "${PYTHON_CMD}" "${GITHUB_ACTION_PATH}"/python_lint.py "${INPUTS_LINTER}" --target="${INPUTS_TARGET}" --output="${GITHUB_WORKSPACE}/${INPUTS_OUTPUT}" || echo "::error::${INPUTS_LINTER} failed to run for Python ${INPUTS_PYTHON_VERSION}"
         else
           echo "::error::invalid linter ${INPUTS_LINTER}; choose one of ${linters[*]}"
         fi
