Better handling of fixit and no results

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,9 +38,9 @@ runs:
         linters=('ruff' 'flake8' 'pylint' 'mypy' 'pyright' 'pytype' 'fixit')
         if [[ "${linters[*]}" =~ (^|[^[:alpha:]])${INPUTS_LINTER}([^[:alpha:]]|$) ]]; then
           if [[ "${INPUTS_LINTER}" == "fixit" ]]; then
-            "${PYTHON_CMD}" -mpip install "fixit >1" --pre
+            "${PYTHON_CMD}" -mpip install "fixit >1" --pre || echo "::error::fixit 2 is not available for python ${INPUTS_PYTHON_VERSION}"
           else
-            "${PYTHON_CMD}" -mpip install "${INPUTS_LINTER}"
+            "${PYTHON_CMD}" -mpip install "${INPUTS_LINTER}" || echo "::error::${INPUTS_LINTER} failed to install for ${INPUTS_PYTHON_VERSION}"
           fi
           if [[ "${INPUTS_LINTER}" == "flake8" ]]; then
             "${PYTHON_CMD}" -mpip install "${GITHUB_ACTION_PATH}"/flake8_sarif_formatter
@@ -56,6 +56,7 @@ runs:
         INPUTS_OUTPUT: ${{ inputs.output }}
       shell: bash
     - name: Upload SARIF
+      if: ${{ fileExists(inputs.output) }}
       uses: github/codeql-action/upload-sarif@v2
       with:
         sarif_file: ${{ inputs.output }}
